name: deploy
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('./package.json', './pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-node${{ matrix.node }}-
      - name: install dependencies
        run: npm install -g pnpm && pnpm install
      - name: deploy
        run: ./deploy
        env:
          DEPLOY_PASS: ${{ secrets.PASSWORD }}
