name: deploy
on: 
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: install dependencies
        run: pnpm install
      - name: deploy
        run: ./deploy
        env:
          DEPLOY_PASS: ${{ secrets.PASSWORD }}
